version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:0.7.0
    container_name: prod_nginx
    restart: always
    volumes:
      # nginx volumes and docker socket are needed for letsencrypt companion
      - nginx_certs:/etc/nginx/certs
      - nginx_dhparam:/etc/nginx/dhparam
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      # docker socket is needed to find containers that have LETSENCRYPT_HOST and VIRTUAL_HOST set
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    logging:
      # For data protection, log is disabled here (as it contains mostly request ips).
      driver: none
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true'

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12
    container_name: prod_nginx_letsencrypt
    restart: always
    volumes:
      - nginx_certs:/etc/nginx/certs
      - nginx_dhparam:/etc/nginx/dhparam
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
      - syslog
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
        tag: "{{.Name}}"

  syslog:
    image: balabit/syslog-ng:3.24.1
    container_name: prod_syslog
    restart: always
    entrypoint:
      - /bin/bash
      - -c
      # Add log-rotation cronjob and run syslog
      - |
        echo '0 1 * * * find /logs/ -name "*.log" -daystart -mtime +14 -type f -exec rm {} \;' | crontab -
        /usr/sbin/syslog-ng -F --no-caps
    volumes:
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro
      - logs:/logs
    ports:
      # Default syslog port is 514/tcp in the docker image
      - 514:514


volumes:
  nginx_dhparam:
  nginx_certs:
  nginx_vhost:
  nginx_html:
  logs:

networks:
  proxy: